//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LayerWebForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginInfo
    {
        public int Lid { get; set; }
        public string Lusername { get; set; }
        public string Luserpwd { get; set; }
        public string Lrealname { get; set; }
    }
}
