//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LayerWebForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StuInfo
    {
        public int Sid { get; set; }
        public Nullable<int> Ssex { get; set; }
        public string Sschool { get; set; }
        public string Sjobname { get; set; }
        public string Sphone { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
        public Nullable<int> Scid { get; set; }
    
        public virtual ClsInfo ClsInfo { get; set; }
    }
}
